<?php

return [
    'judge_credential_id' => env('LLM_JUDGE_CREDENTIAL_ID'),
    'judge_model' => env('LLM_JUDGE_MODEL', 'gemini-1.5-flash'),
    'judge_params' => env('LLM_JUDGE_PARAMS') ? json_decode(env('LLM_JUDGE_PARAMS'), true) : [],
    'models' => [
        'openai' => [
            ['id' => 'o3-mini', 'name' => 'o3-mini', 'display_name' => 'o3-mini'],
            ['id' => 'o1', 'name' => 'o1', 'display_name' => 'o1'],
            ['id' => 'o1-mini', 'name' => 'o1-mini', 'display_name' => 'o1-mini'],
            ['id' => 'gpt-4.1', 'name' => 'gpt-4.1', 'display_name' => 'GPT-4.1'],
            ['id' => 'gpt-4.1-mini', 'name' => 'gpt-4.1-mini', 'display_name' => 'GPT-4.1 Mini'],
            ['id' => 'gpt-4o', 'name' => 'gpt-4o', 'display_name' => 'GPT-4o'],
            ['id' => 'gpt-4o-mini', 'name' => 'gpt-4o-mini', 'display_name' => 'GPT-4o Mini'],
            ['id' => 'gpt-4-turbo', 'name' => 'gpt-4-turbo', 'display_name' => 'GPT-4 Turbo'],
            ['id' => 'gpt-4', 'name' => 'gpt-4', 'display_name' => 'GPT-4'],
            ['id' => 'gpt-3.5-turbo', 'name' => 'gpt-3.5-turbo', 'display_name' => 'GPT-3.5 Turbo'],
        ],
        'anthropic' => [
            ['id' => 'claude-3-5-sonnet-latest', 'name' => 'claude-3-5-sonnet-latest', 'display_name' => 'Claude 3.5 Sonnet (Latest)'],
            ['id' => 'claude-3-5-sonnet-20241022', 'name' => 'claude-3-5-sonnet-20241022', 'display_name' => 'Claude 3.5 Sonnet (Oct 2024)'],
            ['id' => 'claude-3-5-sonnet-20240620', 'name' => 'claude-3-5-sonnet-20240620', 'display_name' => 'Claude 3.5 Sonnet (Jun 2024)'],
            ['id' => 'claude-3-opus-latest', 'name' => 'claude-3-opus-latest', 'display_name' => 'Claude 3 Opus (Latest)'],
            ['id' => 'claude-3-opus-20240229', 'name' => 'claude-3-opus-20240229', 'display_name' => 'Claude 3 Opus (Feb 2024)'],
            ['id' => 'claude-3-sonnet-20240229', 'name' => 'claude-3-sonnet-20240229', 'display_name' => 'Claude 3 Sonnet'],
            ['id' => 'claude-3-haiku-20240307', 'name' => 'claude-3-haiku-20240307', 'display_name' => 'Claude 3 Haiku'],
        ],
        'google' => [
            ['id' => 'gemini-2.0-flash', 'name' => 'gemini-2.0-flash', 'display_name' => 'Gemini 2.0 Flash'],
            ['id' => 'gemini-2.0-flash-lite', 'name' => 'gemini-2.0-flash-lite', 'display_name' => 'Gemini 2.0 Flash Lite'],
            ['id' => 'gemini-1.5-pro', 'name' => 'gemini-1.5-pro', 'display_name' => 'Gemini 1.5 Pro'],
            ['id' => 'gemini-1.5-pro-latest', 'name' => 'gemini-1.5-pro-latest', 'display_name' => 'Gemini 1.5 Pro (Latest)'],
            ['id' => 'gemini-1.5-flash', 'name' => 'gemini-1.5-flash', 'display_name' => 'Gemini 1.5 Flash'],
            ['id' => 'gemini-1.5-flash-latest', 'name' => 'gemini-1.5-flash-latest', 'display_name' => 'Gemini 1.5 Flash (Latest)'],
            ['id' => 'gemini-1.0-pro', 'name' => 'gemini-1.0-pro', 'display_name' => 'Gemini 1.0 Pro'],
        ],
        'openrouter' => [
            ['id' => 'openai/o3-mini', 'name' => 'openai/o3-mini', 'display_name' => 'OpenAI o3-mini'],
            ['id' => 'openai/o1', 'name' => 'openai/o1', 'display_name' => 'OpenAI o1'],
            ['id' => 'openai/gpt-4o', 'name' => 'openai/gpt-4o', 'display_name' => 'OpenAI GPT-4o'],
            ['id' => 'openai/gpt-4o-mini', 'name' => 'openai/gpt-4o-mini', 'display_name' => 'OpenAI GPT-4o Mini'],
            ['id' => 'anthropic/claude-3.5-sonnet', 'name' => 'anthropic/claude-3.5-sonnet', 'display_name' => 'Claude 3.5 Sonnet'],
            ['id' => 'anthropic/claude-3-opus', 'name' => 'anthropic/claude-3-opus', 'display_name' => 'Claude 3 Opus'],
            ['id' => 'anthropic/claude-3-haiku', 'name' => 'anthropic/claude-3-haiku', 'display_name' => 'Claude 3 Haiku'],
            ['id' => 'google/gemini-2.0-flash', 'name' => 'google/gemini-2.0-flash', 'display_name' => 'Gemini 2.0 Flash'],
            ['id' => 'google/gemini-1.5-pro', 'name' => 'google/gemini-1.5-pro', 'display_name' => 'Gemini 1.5 Pro'],
            ['id' => 'google/gemini-1.5-flash', 'name' => 'google/gemini-1.5-flash', 'display_name' => 'Gemini 1.5 Flash'],
            ['id' => 'meta-llama/llama-3.3-70b-instruct', 'name' => 'meta-llama/llama-3.3-70b-instruct', 'display_name' => 'Llama 3.3 70B'],
            ['id' => 'meta-llama/llama-3.2-90b-vision-instruct', 'name' => 'meta-llama/llama-3.2-90b-vision-instruct', 'display_name' => 'Llama 3.2 90B Vision'],
            ['id' => 'mistralai/mistral-large', 'name' => 'mistralai/mistral-large', 'display_name' => 'Mistral Large'],
            ['id' => 'deepseek/deepseek-chat', 'name' => 'deepseek/deepseek-chat', 'display_name' => 'DeepSeek Chat'],
        ],
    ],
];
